### ISSUE TITLE
local test light isn't turning green

### ISSUE THREAD

**Issue by blumaa** [learn-co-curriculum/programming-univbasics-4-building-nested-hashes#1]
Hello my local test light isn't turning green when I run learn. Everything passes but still no green. Nope. No greeney. But I did learn submit and that light turn green green green. Anywho, a little help would be grand. Hasta Luego

**Comment by sgharms** [comment]
Hi there! This request sounds like an improvement to the Learn platform.
[Raising issues on GitHub][issues] should be reserved for problems with the
curriculum itself (doesn't work, throws a Ruby error, etc.)

Our product team loves to hear about our Learners' innovative interface
improvements. You can reach them at support@learn.co. Alternatively, if Learn
is misbehaving, please direct your bug report to bugs@learn.co.

If, on the other hand, we've misunderstood the purpose of this request, please
re-open this issue, provide any additional information you can, and we will try
to discern a proper path to resolution.

[issues]: http://help.learn.co/improving-learn/contributing-to-lessons/raising-an-issue-with-a-lab-or-lesson

Thanks! :blue_heart:
