### ISSUE TITLE
Building Nested Hashes Lab

### ISSUE THREAD

**Issue by emilia-m26** [learn-co-curriculum/programming-univbasics-4-building-nested-hashes#3]
Hello All,

This is my first time opening an issue...

Last test for lab states the following:

    it "sets the 1st key of the :shortline_railroad hash to a string, 'mortgage_value', whose value is also a string, '$400'" do
      expect(monopoly_with_fourth_tier[:railroads][:names][:shortline_railroad]["mortgage_value"]).to eq("$800")

When running the test and following prompts to develop hash, description asks to add value of $400 as string to shortline_railroad, but test is expecting $800.  Small typo in test.

Thanks so much for your time in advance.

**Comment by sgharms** [comment]
Brilliant! Thanks for catching!

**Comment by sgharms** [comment]
Fixed as of 54a6b11! Great help, thanks.
